name: lorecrafter

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pnpm dev --hostname 0.0.0.0
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - pnpm-store:/home/node/.local/share/pnpm
      - node-cache:/home/node/.cache
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"

volumes:
  node-modules:
  pnpm-store:
  node-cache: