#!/usr/bin/env bash
# =========================================================
# Taskfile gives you a set of quick tasks for your project
# More info: https://github.com/Enrise/Taskfile
# =========================================================

function banner {
	echo -e "${BLUE}\n"\
	"██╗      ██████╗ ██████╗ ███████╗ ██████╗██████╗  █████╗ ███████╗████████╗███████╗██████╗ \n"\
	"██║     ██╔═══██╗██╔══██╗██╔════╝██╔════╝██╔══██╗██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗\n"\
	"██║     ██║   ██║██████╔╝█████╗  ██║     ██████╔╝███████║█████╗     ██║   █████╗  ██████╔╝\n"\
	"██║     ██║   ██║██╔══██╗██╔══╝  ██║     ██╔══██╗██╔══██║██╔══╝     ██║   ██╔══╝  ██╔══██╗\n"\
	"███████╗╚██████╔╝██║  ██║███████╗╚██████╗██║  ██║██║  ██║██║        ██║   ███████╗██║  ██║\n"\
	"╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝        ╚═╝   ╚══════╝╚═╝  ╚═╝${RESET}"
}

# =========================================================
## Project
# =========================================================

function task:init { ## Initialise the project for local development
	task:build
	project:update
	task:start
	task:help
}

function task:start { ## Start the project in development mode
	docker:start
	echo -e "Dev server: ${YELLOW}http://localhost:3000${RESET}"
}

function task:update { ## Install dependencies (pnpm install)
	project:update
}

function project:update {
	title "Installing dependencies"
	dockercompose run --rm app pnpm install
}

function task:stop { ## Stop the local project
	docker:stop
}

function task:restart { ## Restart the local project
	docker:stop
	task:start
}

function task:pr { ## Check out pull request <number> and update
	project:checkout-pr $1
	project:update
}

function project:checkout-pr {
	title "Checking out pull request"
	if [ -z "$1" ]; then
		echo "You need to provide a pull request number to check out."
		echo -e "${BLUE}Usage:${RESET} $0 pr ${YELLOW}<number>${RESET}"
		exit 1
	fi
	echo "Checking out pull request $1..."
	git fetch origin refs/pull/$1/head:refs/remotes/origin/pr/$1
	git checkout origin/pr/$1
}

# =========================================================
## Code
# =========================================================

function task:lint { ## Check code with Biome
	title "Linting"
	dockercompose run --rm app pnpm lint
}

function task:format { ## Format code with Biome
	title "Formatting"
	dockercompose run --rm app pnpm format
}

function task:typecheck { ## Check types with TypeScript
	title "Type checking"
	dockercompose run --rm app pnpm typecheck
}

function task:pnpm { ## Run pnpm command <command> in the app container
	title "pnpm $@"
	dockercompose run --rm app pnpm "$@"
}

function task:shell { ## Open a shell in the running app container
	docker:assert-running
	dockercompose exec app bash
}

# =========================================================
## Docker
# =========================================================

function task:build { ## Build all docker compose containers
	title "Building docker compose project"
	dockercompose build
}

function docker:start {
	title "Starting docker compose project"
	dockercompose up --detach
}

function docker:stop {
	title "Stopping docker compose project"
	dockercompose down
}

function task:logs { ## Show the docker compose logs
	title "Following local logs"
	dockercompose logs --tail="20" --follow
}

function task:dc { ## Run docker compose command <command>
	title "Docker compose $@"
	dockercompose "$@"
}

function docker:assert-running {
	if [ -z "$(dockercompose ps -q)" ]; then
		echo -e "${RED}Oh noes, docker was not running yet, starting...${RESET}"
		task:start
		title "Resuming task"
	fi
}

function dockercompose {
	docker compose --file ./compose.yaml "$@"
}

# =========================================================
## Taskfile
# Caution: core functionality, down here be dragons
# =========================================================

set -eo pipefail

BLUE=$(printf '\033[36m')
YELLOW=$(printf '\033[33m')
RED=$(printf '\033[31m')
GREEN=$(printf '\033[32m')
RESET=$(printf '\033[0m')

function run-task {
	if [[ ! "$(declare -F task:${@-help})" ]]; then
		title "Task not found"
		echo -e "Task ${RED}$1${RESET} doesn't exist."
		task:help
		exit 1
	fi
	task:${@-help}
}

function subtaskfile { # use: subtaskfile $SUBTASK_NAME $SUBTASKFILE_PATH
	SUBTASKFILE_TASK="$1" && shift
	SUBTASKFILE_PATH="$1" && shift
	TASKFILE_FILE="$SUBTASKFILE_PATH/SubTaskfile"
	source "$TASKFILE_FILE"
	run-task "$@"
}

function title {
	echo -e "\n${BLUE}=>${RESET} $1\n"
}

function task:help { ## Show all available tasks
	TASKFILE_FILE=${TASKFILE_FILE-$0}
	banner
	title "Available tasks $([[ -n "$SUBTASKFILE_TASK" ]] && echo "for ${YELLOW}$SUBTASKFILE_TASK${RESET}")"
	awk 'BEGIN {FS = " { [#][#][ ]?"} /^([a-zA-Z_-]*:?.*)(\{ )?[#][#][ ]?/ \
		{printf "\033[33m%-34s\033[0m %s\n", $1, $2}' "$TASKFILE_FILE" |\
		sed -E "s/[#]{2,}[ ]*/${RESET}/g" |\
		sed -E "s/function task:*/  /g"
	echo -e "\n${BLUE}Usage:${RESET} ./Taskfile ${YELLOW}$SUBTASKFILE_TASK <task>${RESET} <args>"
}

function task:shorthand { ## Create CLI shorthand task instead of ./Taskfile
	title "Creating task shorthand"
	echo -e "You're about to create ${YELLOW}/usr/local/bin/task${RESET} that requires ${RED}root${RESET} permission..."
	sudo curl --location --silent --output /usr/local/bin/task https://enri.se/taskfile-bin
	sudo chmod +x /usr/local/bin/task
	echo -e "${BLUE}You can now use:${RESET} task ${YELLOW}<task>${RESET} <args>"
}

run-task "$@"
